#
# MakeMKV settings file.
#

app_DataDir = "/config/data"
app_DefaultSelectionString = "+sel:all,-sel:core"
app_DestinationDir = "/remux"
app_DestinationType = "2"
app_ccextractor = "/opt/makemkv/bin/mmccextr"
