#
# MakeMKV settings file.
#

app_DataDir = "/config/data"
app_DefaultSelectionString = "+sel:all,-sel:core"
app_DestinationDir = "/remux"
app_DestinationType = "2"
app_ccextractor = "/opt/makemkv/bin/mmccextr"
app_UpdateEnable = "0"
app_Key = "T-sJ5R5BKxhD671U9s0teXbyP19MhCkkkB7rmnNbb1aEHaqveiVqyI3RXGMHDXhoyNUC"